name: Build Enivronment

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file build-environment-dockerfile --tag duffbeer83/nginx-build-environment:$(date +%s)
